"""Wire existing original caves into an atomic native background bag and an act UI."""
from pathlib import Path
import json,re,subprocess,sys
import numpy as np
from PIL import Image,ImageOps,ImageFilter

ROOT=Path(__file__).resolve().parents[1]
VARIANTS=['cave_skylight','cave_riverbend','cave_quartz','cave_rootfungus',
          'hollow_grotto','hollow_grotto_moss','hollow_grotto_ember','hollow_grotto_violet']

def write(path,text):
    p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text,encoding='utf-8')

root_scene='''[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://src/Core/Nodes/Rooms/NCombatBackground.cs" id="native"]

[node name="DepthsBackground" type="Control"]
mouse_filter = 2
script = ExtResource("native")

[node name="Layer_00" type="Control" parent="."]
unique_name_in_owner = true
mouse_filter = 2

[node name="Foreground" type="Control" parent="."]
unique_name_in_owner = true
mouse_filter = 2
'''
empty_fg='''[gd_scene format=3]

[node name="Foreground" type="Control"]
mouse_filter = 2
'''
for title in ['depths','lantern_fish_encounter','lantern_fish_weak']:
    base=f'scenes/backgrounds/{title}'
    write(f'{base}/{title}_background.tscn',root_scene)
    write(f'{base}/layers/{title}_fg_a.tscn',empty_fg)
    # These two prior files belong to the old single-scene test encounter.
    for old in [f'{title}_bg_00_a.tscn',f'{title}_bg_01_a.tscn']:
        p=ROOT/base/'layers'/old
        assert p.resolve().is_relative_to(ROOT.resolve())
        if p.exists():p.unlink()
    if title!='depths':
        # Remove only the variants previously generated by this script; fish now
        # keep their own riverbank habitat instead of borrowing another room's art.
        for n,variant in enumerate(VARIANTS):
            p=ROOT/base/'layers'/f'{title}_bg_00_{chr(97+n)}_{variant}.tscn'
            assert p.resolve().is_relative_to(ROOT.resolve())
            if p.exists():p.unlink()
    selected=VARIANTS if title=='depths' else ['cave_riverbend']
    for n,variant in enumerate(selected):
        source=ROOT/f'scenes/backgrounds/{variant}/layers'
        layers=sorted(source.glob('*_bg_*.tscn'))+sorted(source.glob('*_fg_*.tscn'))
        assert len(layers)>=3
        # Vanilla chooses each numbered layer independently. Group the complete
        # composition into ONE choice so a river floor can never mix with quartz walls.
        text=f'[gd_scene load_steps={len(layers)+1} format=3]\n\n'
        for i,layer in enumerate(layers):
            text+=f'[ext_resource type="PackedScene" path="res://{layer.relative_to(ROOT).as_posix()}" id="{i}"]\n'
        text+='\n[node name="CompleteCaveVariant" type="Control"]\nmouse_filter = 2\n'
        text+=f'metadata/depths_variant = "{variant}"\n'
        for i,_ in enumerate(layers):text+=f'\n[node name="Layer_{i:02}" parent="." instance=ExtResource("{i}")]\n'
        write(f'{base}/layers/{title}_bg_00_{chr(97+n)}_{variant}.tscn',text)

# Rebuild all three map sections from the selected continuous stone painting.
# Keep the old cave-wash fallback for source checkouts predating that artwork.
if (ROOT/'source_assets/backgrounds/depths_stone_map/selection.json').exists():
    subprocess.run([sys.executable,str(ROOT/'scripts/build_depths_stone_map.py'),'--deploy'],check=True)
else:
    dest=ROOT/'images/packed/map/map_bgs/depths';dest.mkdir(parents=True,exist_ok=True)
    for section,variant in [('top','cave_quartz'),('middle','cave_rootfungus'),('bottom','cave_riverbend')]:
        im=Image.open(ROOT/f'images/rooms/{variant}/{variant}_00.png').convert('RGB')
        im=ImageOps.fit(im,(2036,1440),method=Image.Resampling.LANCZOS).filter(ImageFilter.GaussianBlur(1.4))
        gray=np.asarray(ImageOps.grayscale(im),dtype=float)
        y,x=np.indices(gray.shape);edge=np.abs(x/(gray.shape[1]-1)*2-1)**2
        detail=(gray-128)*(.08+.13*edge)
        out=np.stack([174+detail-8*edge,190+detail-6*edge,194+detail-3*edge],axis=-1)
        Image.fromarray(np.clip(out,0,255).astype('uint8')).save(dest/f'map_{section}_depths.png')

# Dedicated generated camp painting already contains the hearth, wood and seats.
# Only the live flame and light are separate so the native camp can extinguish them.
fire=(ROOT.parent/'STS2-V111/scenes/vfx/fires/vfx_stepped_fire.tscn').read_text(encoding='utf-8-sig')
# The vanilla VFX's unused root ShaderMaterial has no shader. Removing it avoids
# a renderer shutdown warning while retaining every authored flame/spark material.
fire=re.sub(r' uid="[^"]+"','',fire)
fire=fire.replace('[gd_scene load_steps=21','[gd_scene load_steps=20')
fire=fire.replace('[sub_resource type="ShaderMaterial" id="ShaderMaterial_74kop"]\n\n','')
fire=fire.replace('material = SubResource("ShaderMaterial_74kop")\n','')
fire=fire.replace('res://shaders/vfx/vfx_stepped_shader_fire_flat.tres','res://shaders/backgrounds/depths_fire_flat.gdshader')
fire=fire.replace('res://shaders/vfx/vfx_stepped_shader_fire_add.tres','res://shaders/backgrounds/depths_fire_add.gdshader')
write('scenes/rest_site/depths_camp_fire.tscn',fire)
camp_source=ROOT/'source_assets/backgrounds/depths_camp/camp_final.png'
if camp_source.exists():
    camp_target=ROOT/'images/rooms/depths_camp/depths_camp_00.png'
    camp_target.parent.mkdir(parents=True,exist_ok=True)
    ImageOps.fit(Image.open(camp_source).convert('RGB'),(2048,960),method=Image.Resampling.LANCZOS).save(camp_target)
write('scenes/rest_site/depths_rest_site.tscn','''[gd_scene load_steps=7 format=3]

[ext_resource type="Texture2D" path="res://images/rooms/depths_camp/depths_camp_00.png" id="bg"]
[ext_resource type="Material" path="res://materials/backgrounds/cave_readable_new.tres" id="readable"]
[ext_resource type="PackedScene" path="res://scenes/rest_site/depths_camp_fire.tscn" id="fire"]
[ext_resource type="Texture2D" path="res://images/vfx/light.png" id="light"]
[ext_resource type="Shader" path="res://shaders/backgrounds/depths_camp_light.gdshader" id="glow"]

[sub_resource type="ShaderMaterial" id="additive"]
shader = ExtResource("glow")

[node name="DepthsRestSite" type="Control"]
mouse_filter = 2

[node name="Cave" type="TextureRect" parent="."]
material = ExtResource("readable")
offset_left = -444.0
offset_top = -139.0
offset_right = 2320.8
offset_bottom = 1157.0
texture = ExtResource("bg")
expand_mode = 1
mouse_filter = 2

[node name="RestSiteLighting" type="Control" parent="."]
unique_name_in_owner = true
mouse_filter = 2

[node name="WarmLight" type="Sprite2D" parent="RestSiteLighting"]
material = SubResource("additive")
position = Vector2(912, 706)
scale = Vector2(3, 2)
modulate = Color(1, 0.67, 0.30, 0.16)
texture = ExtResource("light")

[node name="Campfire" parent="RestSiteLighting" instance=ExtResource("fire")]
position = Vector2(910, 713)
scale = Vector2(0.42, 0.42)
''')

# Furniture remains separate from the painted plate: the contact points, not the
# image generator's approximate placement, determine where native characters sit.
props_path=ROOT/'source_assets/backgrounds/depths_camp/props.json'
if props_path.exists():
    props=json.loads(props_path.read_text())
    rest_path=ROOT/'scenes/rest_site/depths_rest_site.tscn'
    rest=rest_path.read_text()
    ext=''.join(f'[ext_resource type="Texture2D" path="res://images/rooms/depths_camp/{key}.png" id="{key}"]\n' for key in props)
    rest=rest.replace('[gd_scene load_steps=7','[gd_scene load_steps=14')
    rest=rest.replace('[sub_resource type="ShaderMaterial"',ext+'\n[sub_resource type="ShaderMaterial"',1)
    gradient='''[sub_resource type="Gradient" id="shadow_gradient"]
colors = PackedColorArray(0, 0, 0, 0.25, 0, 0, 0, 0)

[sub_resource type="GradientTexture2D" id="shadow"]
gradient = SubResource("shadow_gradient")
width = 256
height = 128
fill = 1
fill_from = Vector2(0.5, 0.5)
fill_to = Vector2(0.5, 0)

'''
    rest=rest.replace('[node name="DepthsRestSite"',gradient+'[node name="DepthsRestSite"',1)
    furniture=''
    for key in ['seat_back_left','seat_back_right','seat_front_left','seat_front_right','hearth']:
        p=props[key];x,y=p['position'];sx,sy=p['scale'];ax,ay=p['anchor'];l,t,r,b=p['source_box']
        furniture+=f'''[node name="{key}_shadow" type="Sprite2D" parent="."]
position = Vector2({x}, {y+(b-t-ay)*sy-5})
scale = Vector2({(r-l)*sx/256}, 0.2)
texture = SubResource("shadow")

[node name="{key}" type="Sprite2D" parent="."]
position = Vector2({x}, {y})
scale = Vector2({sx}, {sy})
texture = ExtResource("{key}")
centered = false
offset = Vector2({-ax}, {-ay})

'''
    rest=rest.replace('[node name="RestSiteLighting"',furniture+'[node name="RestSiteLighting"',1)
    rest_path.write_text(rest,encoding='utf-8')

def update_locale(lang,table,entries):
    path=ROOT/f'STS2_Things/localization/{lang}/{table}.json'
    raw=path.read_text(encoding='utf-8-sig') if path.exists() else '{}\n'
    current=json.loads(raw)
    for key,value in entries.items():
        if key in current:
            pattern=r'("'+re.escape(key)+r'"\s*:\s*)"(?:\\.|[^"\\])*"'
            raw=re.sub(pattern,lambda m:m.group(1)+json.dumps(value,ensure_ascii=False),raw)
        else:
            end=raw.rfind('}');prefix=raw[:end].rstrip()
            raw=prefix+(',' if len(current) else '')+'\n  '+json.dumps(key)+': '+json.dumps(value,ensure_ascii=False)+'\n}\n'
        current[key]=value
    path.write_text(raw,encoding='utf-8')
for lang,title in [('zhs','深处'),('eng','Depths')]:update_locale(lang,'acts',{'DEPTHS.title':title})
update_locale('zhs','encounters',{'LANTERN_FISH_ENCOUNTER.title':'灯笼鱼群','LANTERN_FISH_WEAK.title':'结伴灯笼鱼',
    'LANTERN_FISH_WEAK.loss':'{character}在[gold]{encounter}[/gold]的强光中失去了方向……'})
update_locale('eng','encounters',{'LANTERN_FISH_ENCOUNTER.title':'Lantern Fish Shoal','LANTERN_FISH_WEAK.title':'Lantern Fish Pair',
    'LANTERN_FISH_WEAK.loss':'{character} lost their bearings in the light of [gold]{encounter}[/gold].'})
write('design/depths_background_variants.json',json.dumps(VARIANTS,indent=2)+'\n')
print('Depths assets ready: 8 act backgrounds, fixed riverbank fish scenes, dedicated campsite, map textures and localization.')
