// Generated by scripts/build_cavegod_contact.mjs from the original Spine mesh poses.
using Godot;

namespace STS2_Things.Visuals;

internal readonly record struct CaveGodContactProfile(string Clip, float Start, float Hit, float Hold, float End, bool Left, bool Paired, bool Grab, Vector2 Center, Vector2 PalmOffset, Vector2 Size);

internal static class CaveGodContactProfiles
{
    internal static readonly CaveGodContactProfile[] All =
    [
        new("alternating_jabs", 0.32000f, 0.64000f, 0.72000f, 1.00000f, true, false, false, new Vector2(-87.29317f, -187.48866f), new Vector2(74.32887f, -56.38585f), new Vector2(287.51434f, 225.95354f)),
        new("alternating_jabs", 1.02000f, 1.34000f, 1.42000f, 1.70000f, false, false, false, new Vector2(73.06318f, -184.11148f), new Vector2(-68.19306f, -32.29676f), new Vector2(279.07236f, 223.12585f)),
        new("alternating_jabs", 1.90000f, 2.32000f, 2.42000f, 3.35000f, true, false, false, new Vector2(-94.36822f, -187.73482f), new Vector2(84.24138f, -63.62116f), new Vector2(312.81059f, 246.52389f)),
        new("alternating_jabs_angry", 0.32000f, 0.64000f, 0.72000f, 1.00000f, true, false, false, new Vector2(-87.29317f, -187.48866f), new Vector2(74.32887f, -56.38585f), new Vector2(287.51434f, 225.95354f)),
        new("alternating_jabs_angry", 1.02000f, 1.34000f, 1.42000f, 1.70000f, false, false, false, new Vector2(73.06318f, -184.11148f), new Vector2(-68.19306f, -32.29676f), new Vector2(279.07236f, 223.12585f)),
        new("alternating_jabs_angry", 1.90000f, 2.32000f, 2.42000f, 3.35000f, true, false, false, new Vector2(-94.36822f, -187.73482f), new Vector2(84.24138f, -63.62116f), new Vector2(312.81059f, 246.52389f)),
        new("central_slam", 1.05000f, 1.88000f, 2.10000f, 3.60000f, true, true, false, new Vector2(-157.75154f, -215.16794f), new Vector2(-6.20549f, -64.00254f), new Vector2(284.75669f, 185.52740f)),
        new("central_slam", 1.05000f, 1.88000f, 2.10000f, 3.60000f, false, true, false, new Vector2(159.30869f, -206.38021f), new Vector2(7.17406f, -55.21630f), new Vector2(287.10144f, 169.48091f)),
        new("central_slam_angry", 1.05000f, 1.88000f, 2.10000f, 3.60000f, true, true, false, new Vector2(-157.75154f, -215.16794f), new Vector2(-6.20549f, -64.00254f), new Vector2(284.75669f, 185.52740f)),
        new("central_slam_angry", 1.05000f, 1.88000f, 2.10000f, 3.60000f, false, true, false, new Vector2(159.30869f, -206.38021f), new Vector2(7.17406f, -55.21630f), new Vector2(287.10144f, 169.48091f)),
        new("double_fist_crush", 0.65000f, 1.25000f, 1.53000f, 3.18000f, true, true, false, new Vector2(-56.24269f, -160.45605f), new Vector2(50.13418f, -69.17828f), new Vector2(239.97642f, 231.31837f)),
        new("double_fist_crush", 0.65000f, 1.25000f, 1.53000f, 3.18000f, false, true, false, new Vector2(61.43821f, -158.05890f), new Vector2(-45.58205f, -46.65228f), new Vector2(241.56496f, 224.98607f)),
        new("double_fist_crush_angry", 0.65000f, 1.25000f, 1.53000f, 3.18000f, true, true, false, new Vector2(-56.24269f, -160.45605f), new Vector2(50.13418f, -69.17828f), new Vector2(239.97642f, 231.31837f)),
        new("double_fist_crush_angry", 0.65000f, 1.25000f, 1.53000f, 3.18000f, false, true, false, new Vector2(61.43821f, -158.05890f), new Vector2(-45.58205f, -46.65228f), new Vector2(241.56496f, 224.98607f)),
        new("front_sweep", 0.76000f, 1.35000f, 1.48000f, 3.22000f, true, false, false, new Vector2(-95.24548f, -229.54409f), new Vector2(76.70897f, 11.13390f), new Vector2(269.15748f, 225.10261f)),
        new("front_sweep_angry", 0.76000f, 1.35000f, 1.48000f, 3.22000f, true, false, false, new Vector2(-95.24548f, -229.54409f), new Vector2(76.70897f, 11.13390f), new Vector2(269.15748f, 225.10261f)),
        new("front_sweep_right", 0.76000f, 1.35000f, 1.48000f, 3.22000f, false, false, false, new Vector2(175.95282f, -162.63377f), new Vector2(-60.26654f, 18.46499f), new Vector2(245.57123f, 229.58030f)),
        new("front_sweep_right_angry", 0.76000f, 1.35000f, 1.48000f, 3.22000f, false, false, false, new Vector2(175.95282f, -162.63377f), new Vector2(-60.26654f, 18.46499f), new Vector2(245.57123f, 229.58030f)),
        new("card_snatch", 1.00000f, 1.36000f, 1.68000f, 3.08000f, true, false, false, new Vector2(-22.94657f, -170.91028f), new Vector2(56.25180f, -55.54634f), new Vector2(202.19571f, 274.03558f)),
        new("card_snatch_angry", 1.00000f, 1.36000f, 1.68000f, 3.08000f, true, false, false, new Vector2(-22.94657f, -170.91028f), new Vector2(56.25180f, -55.54634f), new Vector2(202.19571f, 274.03558f)),
        new("card_snatch_right", 1.00000f, 1.36000f, 1.68000f, 3.08000f, false, false, false, new Vector2(40.50192f, -171.41679f), new Vector2(-39.42678f, -55.84864f), new Vector2(212.60751f, 254.09550f)),
        new("card_snatch_right_angry", 1.00000f, 1.36000f, 1.68000f, 3.08000f, false, false, false, new Vector2(40.50192f, -171.41679f), new Vector2(-39.42678f, -55.84864f), new Vector2(212.60751f, 254.09550f)),
        new("weak_attack", 0.60000f, 1.20000f, 1.35000f, 2.50000f, false, false, false, new Vector2(53.99691f, -186.07354f), new Vector2(-77.47734f, -38.92963f), new Vector2(271.64446f, 243.73659f)),
        new("weak_attack_angry", 0.60000f, 1.20000f, 1.35000f, 2.50000f, false, false, false, new Vector2(53.99691f, -186.07354f), new Vector2(-77.47734f, -38.92963f), new Vector2(271.64446f, 243.73659f)),
        new("weak_attack_right", 0.60000f, 1.20000f, 1.35000f, 2.50000f, true, false, false, new Vector2(-51.53381f, -209.84723f), new Vector2(79.62842f, -63.46937f), new Vector2(285.40073f, 252.73755f)),
        new("weak_attack_right_angry", 0.60000f, 1.20000f, 1.35000f, 2.50000f, true, false, false, new Vector2(-51.53381f, -209.84723f), new Vector2(79.62842f, -63.46937f), new Vector2(285.40073f, 252.73755f)),
        new("grab_player", 0.65000f, 1.10000f, 1.28000f, 2.20000f, true, false, true, new Vector2(1.18957f, -185.59385f), new Vector2(62.71323f, -44.41156f), new Vector2(251.11048f, 200.76030f)),
        new("grab_player_angry", 0.65000f, 1.10000f, 1.28000f, 2.20000f, true, false, true, new Vector2(1.18957f, -185.59385f), new Vector2(62.71323f, -44.41156f), new Vector2(251.11048f, 200.76030f)),
        new("grab_player_right", 0.65000f, 1.10000f, 1.28000f, 2.20000f, false, false, true, new Vector2(6.96608f, -165.63501f), new Vector2(-55.34599f, -25.05627f), new Vector2(247.71313f, 195.94006f)),
        new("grab_player_right_angry", 0.65000f, 1.10000f, 1.28000f, 2.20000f, false, false, true, new Vector2(6.96608f, -165.63501f), new Vector2(-55.34599f, -25.05627f), new Vector2(247.71313f, 195.94006f)),
        new("grab_slam", 0.22000f, 0.75000f, 0.83000f, 1.62000f, true, false, true, new Vector2(10.29959f, -179.51311f), new Vector2(71.57238f, -31.87166f), new Vector2(251.46476f, 211.64260f)),
        new("grab_slam_angry", 0.22000f, 0.75000f, 0.83000f, 1.62000f, true, false, true, new Vector2(10.29959f, -179.51311f), new Vector2(71.57238f, -31.87166f), new Vector2(251.46476f, 211.64260f)),
        new("grab_slam_right", 0.22000f, 0.75000f, 0.83000f, 1.62000f, false, false, true, new Vector2(-1.17691f, -164.34308f), new Vector2(-63.20243f, -16.63684f), new Vector2(246.70242f, 201.46477f)),
        new("grab_slam_right_angry", 0.22000f, 0.75000f, 0.83000f, 1.62000f, false, false, true, new Vector2(-1.17691f, -164.34308f), new Vector2(-63.20243f, -16.63684f), new Vector2(246.70242f, 201.46477f)),
    ];
}
