// <auto-generated />
using System.Collections.Generic;
using Godot;

namespace STS2_Things.Visuals;

internal readonly record struct CutoutBoneSpec(
    string Name,
    string ParentBoneName,
    Vector2 PivotPosition);

internal readonly record struct CutoutPartSpec(
    string Name,
    string BoneName,
    string TexturePath,
    Vector2 PivotPosition,
    Vector2 SpriteOffset,
    int ZIndex,
    int JointOverlapPixels,
    int AtlasBleedPixels,
    bool IsUnderlay,
    string SemanticRole);

internal static class GeneratedCutoutRigData
{
    private static readonly CutoutBoneSpec[] OriginFogmogBones =
    [
        new("Root", "", new Vector2(0.000f, 373.000f)),
        new("Body", "Root", new Vector2(0.000f, 143.000f)),
        new("Face", "Body", new Vector2(-5.000f, -22.000f)),
        new("CapCenter", "Face", new Vector2(0.000f, -177.000f)),
        new("CapLeft", "CapCenter", new Vector2(-183.000f, -191.000f)),
        new("CapRight", "CapCenter", new Vector2(207.000f, -197.000f)),
        new("LeftArm", "Body", new Vector2(-121.000f, 10.000f)),
        new("LeftForearm", "LeftArm", new Vector2(-214.000f, 125.000f)),
        new("LeftHand", "LeftForearm", new Vector2(-306.000f, 223.000f)),
        new("RightArm", "Body", new Vector2(125.000f, -4.000f)),
        new("RightForearm", "RightArm", new Vector2(229.000f, 108.000f)),
        new("RightHand", "RightForearm", new Vector2(317.000f, 215.000f)),
        new("LeftLeg", "Body", new Vector2(-106.000f, 259.000f)),
        new("LeftFoot", "LeftLeg", new Vector2(-125.000f, 367.000f)),
        new("RightLeg", "Body", new Vector2(128.000f, 259.000f)),
        new("RightFoot", "RightLeg", new Vector2(165.000f, 372.000f)),
    ];

    private static readonly CutoutBoneSpec[] BowlbugProgenitorBones =
    [
        new("Root", "", new Vector2(26.500f, 129.000f)),
        new("FrontShell", "Root", new Vector2(-118.500f, 74.000f)),
        new("Head", "FrontShell", new Vector2(-298.500f, 119.000f)),
        new("Crest", "Head", new Vector2(-298.500f, -41.000f)),
        new("MidShell", "Root", new Vector2(146.500f, 79.000f)),
        new("RearShell", "Root", new Vector2(541.500f, 109.000f)),
        new("Mandible", "Head", new Vector2(-603.500f, 199.000f)),
        new("MandibleLower", "Head", new Vector2(-613.500f, 255.000f)),
        new("FrontLeg", "FrontShell", new Vector2(-143.500f, 201.000f)),
        new("FrontLegLower", "FrontLeg", new Vector2(-238.500f, 269.000f)),
        new("FrontFoot", "FrontLegLower", new Vector2(-292.500f, 356.000f)),
        new("MidLegA", "MidShell", new Vector2(-28.500f, 204.000f)),
        new("MidLegALower", "MidLegA", new Vector2(1.500f, 280.000f)),
        new("MidFootA", "MidLegALower", new Vector2(29.500f, 356.000f)),
        new("EggSac", "Root", new Vector2(341.500f, 84.000f)),
        new("MidLegB", "EggSac", new Vector2(226.500f, 204.000f)),
        new("MidLegBLower", "MidLegB", new Vector2(265.500f, 290.000f)),
        new("MidFootB", "MidLegBLower", new Vector2(301.500f, 353.000f)),
        new("RearLegA", "RearShell", new Vector2(409.500f, 204.000f)),
        new("RearLegALower", "RearLegA", new Vector2(463.500f, 285.000f)),
        new("RearFootA", "RearLegALower", new Vector2(535.500f, 351.000f)),
        new("RearLegB", "RearShell", new Vector2(601.500f, 204.000f)),
        new("RearLegBLower", "RearLegB", new Vector2(645.500f, 275.000f)),
        new("RearFootB", "RearLegBLower", new Vector2(692.500f, 329.000f)),
    ];

    private static readonly CutoutBoneSpec[] ScaleBeetleBones =
    [
        new("Root", "", new Vector2(46.500f, 208.500f)),
        new("FrontShell", "Root", new Vector2(-58.500f, 113.500f)),
        new("Head", "FrontShell", new Vector2(-213.500f, 158.500f)),
        new("AntennaFrontBase", "Head", new Vector2(-437.500f, 110.500f)),
        new("AntennaFront1", "AntennaFrontBase", new Vector2(-426.500f, 40.500f)),
        new("AntennaFront2", "AntennaFront1", new Vector2(-397.500f, -67.500f)),
        new("AntennaFront3", "AntennaFront2", new Vector2(-342.500f, -149.500f)),
        new("AntennaFront4", "AntennaFront3", new Vector2(-264.500f, -224.500f)),
        new("AntennaFront5", "AntennaFront4", new Vector2(-171.500f, -278.500f)),
        new("AntennaFrontTip", "AntennaFront5", new Vector2(-89.500f, -295.500f)),
        new("AntennaBackBase", "Head", new Vector2(-462.500f, 107.500f)),
        new("AntennaBack1", "AntennaBackBase", new Vector2(-479.500f, 44.500f)),
        new("AntennaBack2", "AntennaBack1", new Vector2(-480.500f, -57.500f)),
        new("AntennaBack3", "AntennaBack2", new Vector2(-443.500f, -155.500f)),
        new("AntennaBack4", "AntennaBack3", new Vector2(-377.500f, -241.500f)),
        new("AntennaBack5", "AntennaBack4", new Vector2(-303.500f, -320.500f)),
        new("AntennaBackTip", "AntennaBack5", new Vector2(-233.500f, -382.500f)),
        new("JawUpper", "Head", new Vector2(-398.500f, 218.500f)),
        new("JawLower", "Head", new Vector2(-383.500f, 248.500f)),
        new("ForeClaw", "FrontShell", new Vector2(-133.500f, 238.500f)),
        new("ForeClawLower", "ForeClaw", new Vector2(-230.500f, 313.500f)),
        new("FrontLeg", "FrontShell", new Vector2(-33.500f, 238.500f)),
        new("FrontLegLower", "FrontLeg", new Vector2(-3.500f, 302.500f)),
        new("FrontFoot", "FrontLegLower", new Vector2(-34.500f, 362.500f)),
        new("Core", "Root", new Vector2(126.500f, 103.500f)),
        new("MidLeg", "Core", new Vector2(56.500f, 208.500f)),
        new("MidLegLower", "MidLeg", new Vector2(92.500f, 302.500f)),
        new("MidFoot", "MidLegLower", new Vector2(126.500f, 404.500f)),
        new("RearShell", "Root", new Vector2(336.500f, 123.500f)),
        new("RearLeg", "RearShell", new Vector2(302.500f, 183.500f)),
        new("RearLegLower", "RearLeg", new Vector2(347.500f, 293.500f)),
        new("RearFoot", "RearLegLower", new Vector2(394.500f, 400.500f)),
    ];

    private static readonly CutoutBoneSpec[] SoulRoe1Bones =
    [
        new("Root", "", new Vector2(0.000f, 0.000f)),
        new("Core", "Root", new Vector2(0.000f, 4.000f)),
        new("Nucleus", "Core", new Vector2(0.000f, 4.000f)),
    ];

    private static readonly CutoutBoneSpec[] SoulRoe2Bones =
    [
        new("Root", "", new Vector2(0.000f, 0.000f)),
        new("Core", "Root", new Vector2(0.000f, 4.000f)),
        new("Nucleus", "Core", new Vector2(0.000f, 4.000f)),
    ];

    private static readonly CutoutBoneSpec[] SoulRoe3Bones =
    [
        new("Root", "", new Vector2(0.000f, 0.000f)),
        new("Core", "Root", new Vector2(0.000f, 4.000f)),
        new("Nucleus", "Core", new Vector2(0.000f, 4.000f)),
    ];

    private static readonly CutoutBoneSpec[] SoulRoesBones =
    [
        new("Root", "", new Vector2(-0.500f, 0.500f)),
        new("ClusterBottom", "Root", new Vector2(1.500f, 80.500f)),
        new("RoeBottomRight", "ClusterBottom", new Vector2(81.500f, 86.500f)),
        new("RoeBottom", "ClusterBottom", new Vector2(-0.500f, 81.500f)),
        new("RoeBottomLeft", "ClusterBottom", new Vector2(-74.500f, 74.500f)),
        new("ClusterMiddle", "Root", new Vector2(-0.500f, 5.500f)),
        new("RoeFarRight", "ClusterMiddle", new Vector2(144.500f, 43.500f)),
        new("RoeBottomFarRight", "ClusterBottom", new Vector2(131.500f, 35.500f)),
        new("RoeMiddleLeft", "ClusterMiddle", new Vector2(-63.500f, -1.500f)),
        new("RoeMiddleFarLeft", "ClusterMiddle", new Vector2(-140.500f, 5.500f)),
        new("RoeCore", "ClusterMiddle", new Vector2(4.500f, -14.500f)),
        new("RoeMiddleRight", "ClusterMiddle", new Vector2(91.500f, -24.500f)),
        new("ClusterTop", "Root", new Vector2(-0.500f, -74.500f)),
        new("RoeTopLeft", "ClusterTop", new Vector2(-98.500f, -67.500f)),
        new("RoeTop", "ClusterTop", new Vector2(-33.500f, -91.500f)),
        new("RoeTopRight", "ClusterTop", new Vector2(41.500f, -84.500f)),
    ];

    private static readonly CutoutBoneSpec[] TheLegacyBones =
    [
        new("Root", "", new Vector2(1.000f, 215.500f)),
        new("HeartAnchor", "Root", new Vector2(11.000f, 85.500f)),
        new("CoralLeft", "HeartAnchor", new Vector2(-379.000f, 85.500f)),
        new("CoralRight", "HeartAnchor", new Vector2(126.000f, 215.500f)),
        new("SeaweedLeft", "Root", new Vector2(-419.000f, 5.500f)),
        new("TopPurple", "HeartAnchor", new Vector2(111.000f, -174.500f)),
        new("TopTubes", "TopPurple", new Vector2(11.000f, -229.500f)),
        new("LeftTubes", "HeartAnchor", new Vector2(-329.000f, -69.500f)),
        new("LeftLobe", "HeartAnchor", new Vector2(-339.000f, 85.500f)),
        new("BottomLobe", "HeartAnchor", new Vector2(-259.000f, 220.500f)),
        new("HeartCore", "HeartAnchor", new Vector2(11.000f, 85.500f)),
        new("RightLobe", "HeartAnchor", new Vector2(251.000f, 95.500f)),
        new("RightTubes", "HeartAnchor", new Vector2(441.000f, 65.500f)),
        new("RightPurpleTubes", "HeartAnchor", new Vector2(551.000f, 175.500f)),
    ];

    private static readonly CutoutBoneSpec[] ThiefRaiderBones =
    [
        new("Root", "", new Vector2(13.500f, 219.000f)),
        new("Pelvis", "Root", new Vector2(13.500f, 18.000f)),
        new("Torso", "Pelvis", new Vector2(13.500f, -32.000f)),
        new("DaggerUpperArm", "Torso", new Vector2(83.500f, -97.000f)),
        new("DaggerForearm", "DaggerUpperArm", new Vector2(105.500f, -32.000f)),
        new("DaggerHand", "DaggerForearm", new Vector2(120.500f, 23.000f)),
        new("Dagger", "DaggerHand", new Vector2(133.500f, 33.000f)),
        new("GuardArm", "Torso", new Vector2(-56.500f, -132.000f)),
        new("GuardForearm", "GuardArm", new Vector2(-71.500f, -82.000f)),
        new("GuardHand", "GuardForearm", new Vector2(-13.500f, -95.000f)),
        new("Scarf", "Torso", new Vector2(30.500f, -122.000f)),
        new("Head", "Torso", new Vector2(13.500f, -142.000f)),
        new("LeftLeg", "Pelvis", new Vector2(-31.500f, 53.000f)),
        new("LeftShin", "LeftLeg", new Vector2(-41.500f, 143.000f)),
        new("LeftFoot", "LeftShin", new Vector2(-58.500f, 228.000f)),
        new("RightLeg", "Pelvis", new Vector2(43.500f, 53.000f)),
        new("RightShin", "RightLeg", new Vector2(48.500f, 138.000f)),
        new("RightFoot", "RightShin", new Vector2(75.500f, 218.000f)),
        new("Bag", "Torso", new Vector2(-50.500f, -122.000f)),
        new("Cloak", "Torso", new Vector2(-31.500f, -77.000f)),
        new("CloakLeftTail", "Cloak", new Vector2(-107.500f, 33.000f)),
        new("CloakRightTail", "Cloak", new Vector2(-26.500f, 48.000f)),
    ];

    private static readonly CutoutPartSpec[] OriginFogmog =
    [
        new("base", "Body", "res://images/monsters/rig_parts/origin_fogmog/base.png", new Vector2(0.000f, 143.000f), new Vector2(297.500f, 5.000f), 0, 0, 2, false, "base"),
        new("face_features", "Face", "res://images/monsters/rig_parts/origin_fogmog/face_features.png", new Vector2(-5.000f, -22.000f), new Vector2(-17.500f, -56.000f), 48, 4, 2, false, "accent"),
        new("cap_left", "CapLeft", "res://images/monsters/rig_parts/origin_fogmog/cap_left.png", new Vector2(-183.000f, -191.000f), new Vector2(-50.000f, -74.500f), 45, 12, 2, false, "cap"),
        new("cap_center", "CapCenter", "res://images/monsters/rig_parts/origin_fogmog/cap_center.png", new Vector2(0.000f, -177.000f), new Vector2(44.000f, -127.000f), 47, 12, 2, false, "cap"),
        new("cap_right", "CapRight", "res://images/monsters/rig_parts/origin_fogmog/cap_right.png", new Vector2(207.000f, -197.000f), new Vector2(92.500f, -89.500f), 44, 12, 2, false, "cap"),
        new("cap_underside", "CapCenter", "res://images/monsters/rig_parts/origin_fogmog/cap_underside.png", new Vector2(0.000f, -177.000f), new Vector2(-76.500f, 52.500f), 43, 8, 2, false, "cap_underlay"),
        new("left_hand", "LeftHand", "res://images/monsters/rig_parts/origin_fogmog/left_hand.png", new Vector2(-306.000f, 223.000f), new Vector2(36.000f, 19.500f), 34, 14, 2, false, "hand"),
        new("left_forearm", "LeftForearm", "res://images/monsters/rig_parts/origin_fogmog/left_forearm.png", new Vector2(-214.000f, 125.000f), new Vector2(4.500f, 8.500f), 31, 16, 2, false, "limb"),
        new("left_upper_arm", "LeftArm", "res://images/monsters/rig_parts/origin_fogmog/left_upper_arm.png", new Vector2(-121.000f, 10.000f), new Vector2(-7.500f, 29.000f), 30, 20, 2, false, "limb"),
        new("right_hand", "RightHand", "res://images/monsters/rig_parts/origin_fogmog/right_hand.png", new Vector2(317.000f, 215.000f), new Vector2(10.000f, 31.000f), 34, 14, 2, false, "hand"),
        new("right_forearm", "RightForearm", "res://images/monsters/rig_parts/origin_fogmog/right_forearm.png", new Vector2(229.000f, 108.000f), new Vector2(39.000f, 21.500f), 31, 16, 2, false, "limb"),
        new("right_upper_arm", "RightArm", "res://images/monsters/rig_parts/origin_fogmog/right_upper_arm.png", new Vector2(125.000f, -4.000f), new Vector2(42.000f, 29.000f), 30, 20, 2, false, "limb"),
        new("left_foot", "LeftFoot", "res://images/monsters/rig_parts/origin_fogmog/left_foot.png", new Vector2(-125.000f, 367.000f), new Vector2(-5.000f, 17.500f), 23, 16, 2, false, "foot"),
        new("left_leg", "LeftLeg", "res://images/monsters/rig_parts/origin_fogmog/left_leg.png", new Vector2(-106.000f, 259.000f), new Vector2(14.500f, 18.000f), 21, 18, 2, false, "limb"),
        new("right_foot", "RightFoot", "res://images/monsters/rig_parts/origin_fogmog/right_foot.png", new Vector2(165.000f, 372.000f), new Vector2(6.000f, 23.000f), 23, 16, 2, false, "foot"),
        new("right_leg", "RightLeg", "res://images/monsters/rig_parts/origin_fogmog/right_leg.png", new Vector2(128.000f, 259.000f), new Vector2(21.000f, 17.000f), 21, 18, 2, false, "limb"),
        new("body_core", "Body", "res://images/monsters/rig_parts/origin_fogmog/body_core.png", new Vector2(0.000f, 143.000f), new Vector2(36.000f, -47.000f), 20, 10, 2, false, "core"),
        new("socket_left_shoulder", "Body", "res://images/monsters/rig_parts/origin_fogmog/socket_left_shoulder.png", new Vector2(0.000f, 143.000f), new Vector2(-115.500f, -134.500f), 24, 0, 2, true, "socket"),
        new("socket_right_shoulder", "Body", "res://images/monsters/rig_parts/origin_fogmog/socket_right_shoulder.png", new Vector2(0.000f, 143.000f), new Vector2(127.500f, -149.500f), 24, 0, 2, true, "socket"),
        new("socket_left_hip", "Body", "res://images/monsters/rig_parts/origin_fogmog/socket_left_hip.png", new Vector2(0.000f, 143.000f), new Vector2(-100.000f, 123.000f), 18, 0, 2, true, "socket"),
        new("socket_right_hip", "Body", "res://images/monsters/rig_parts/origin_fogmog/socket_right_hip.png", new Vector2(0.000f, 143.000f), new Vector2(130.000f, 123.000f), 18, 0, 2, true, "socket"),
    ];

    private static readonly CutoutPartSpec[] BowlbugProgenitor =
    [
        new("base", "Root", "res://images/monsters/rig_parts/bowlbug_progenitor/base.png", new Vector2(26.500f, 129.000f), new Vector2(-91.500f, 71.500f), 0, 0, 2, false, "base"),
        new("gem_head_crown", "Crest", "res://images/monsters/rig_parts/bowlbug_progenitor/gem_head_crown.png", new Vector2(-298.500f, -41.000f), new Vector2(-155.500f, -142.000f), 50, 2, 2, false, "accent"),
        new("gem_head_brow", "Head", "res://images/monsters/rig_parts/bowlbug_progenitor/gem_head_brow.png", new Vector2(-298.500f, 119.000f), new Vector2(-211.500f, -161.000f), 50, 2, 2, false, "accent"),
        new("gem_crest_front", "Crest", "res://images/monsters/rig_parts/bowlbug_progenitor/gem_crest_front.png", new Vector2(-298.500f, -41.000f), new Vector2(-84.500f, -39.500f), 50, 2, 2, false, "accent"),
        new("gem_crest_mid", "Crest", "res://images/monsters/rig_parts/bowlbug_progenitor/gem_crest_mid.png", new Vector2(-298.500f, -41.000f), new Vector2(205.500f, -164.500f), 50, 2, 2, false, "accent"),
        new("gem_front_shell_top", "FrontShell", "res://images/monsters/rig_parts/bowlbug_progenitor/gem_front_shell_top.png", new Vector2(-118.500f, 74.000f), new Vector2(110.500f, -373.000f), 50, 2, 2, false, "accent"),
        new("gem_front_shell_low", "FrontShell", "res://images/monsters/rig_parts/bowlbug_progenitor/gem_front_shell_low.png", new Vector2(-118.500f, 74.000f), new Vector2(250.500f, -249.500f), 50, 2, 2, false, "accent"),
        new("gem_mid_shell", "MidShell", "res://images/monsters/rig_parts/bowlbug_progenitor/gem_mid_shell.png", new Vector2(146.500f, 79.000f), new Vector2(155.500f, -414.000f), 50, 2, 2, false, "accent"),
        new("gem_rear_shell", "RearShell", "res://images/monsters/rig_parts/bowlbug_progenitor/gem_rear_shell.png", new Vector2(541.500f, 109.000f), new Vector2(-67.500f, -409.500f), 50, 2, 2, false, "accent"),
        new("gem_tail", "RearShell", "res://images/monsters/rig_parts/bowlbug_progenitor/gem_tail.png", new Vector2(541.500f, 109.000f), new Vector2(146.500f, -119.500f), 50, 2, 2, false, "accent"),
        new("mandible_upper", "Mandible", "res://images/monsters/rig_parts/bowlbug_progenitor/mandible_upper.png", new Vector2(-603.500f, 199.000f), new Vector2(-41.500f, 4.500f), 46, 12, 2, false, "jaw"),
        new("mandible_lower", "MandibleLower", "res://images/monsters/rig_parts/bowlbug_progenitor/mandible_lower.png", new Vector2(-613.500f, 255.000f), new Vector2(23.500f, 1.500f), 47, 12, 2, false, "jaw"),
        new("front_foot", "FrontFoot", "res://images/monsters/rig_parts/bowlbug_progenitor/front_foot.png", new Vector2(-292.500f, 356.000f), new Vector2(7.000f, -9.500f), 36, 10, 2, false, "foot"),
        new("front_leg_lower", "FrontLegLower", "res://images/monsters/rig_parts/bowlbug_progenitor/front_leg_lower.png", new Vector2(-238.500f, 269.000f), new Vector2(-19.500f, 0.500f), 35, 14, 2, false, "limb"),
        new("front_leg", "FrontLeg", "res://images/monsters/rig_parts/bowlbug_progenitor/front_leg.png", new Vector2(-143.500f, 201.000f), new Vector2(-47.500f, 2.500f), 34, 20, 2, false, "limb"),
        new("mid_foot_a", "MidFootA", "res://images/monsters/rig_parts/bowlbug_progenitor/mid_foot_a.png", new Vector2(29.500f, 356.000f), new Vector2(-7.000f, -8.500f), 35, 10, 2, false, "foot"),
        new("mid_leg_a_lower", "MidLegALower", "res://images/monsters/rig_parts/bowlbug_progenitor/mid_leg_a_lower.png", new Vector2(1.500f, 280.000f), new Vector2(0.500f, -6.500f), 34, 14, 2, false, "limb"),
        new("mid_leg_a", "MidLegA", "res://images/monsters/rig_parts/bowlbug_progenitor/mid_leg_a.png", new Vector2(-28.500f, 204.000f), new Vector2(5.500f, 8.000f), 33, 20, 2, false, "limb"),
        new("mid_foot_b", "MidFootB", "res://images/monsters/rig_parts/bowlbug_progenitor/mid_foot_b.png", new Vector2(301.500f, 353.000f), new Vector2(12.500f, -9.500f), 35, 10, 2, false, "foot"),
        new("mid_leg_b_lower", "MidLegBLower", "res://images/monsters/rig_parts/bowlbug_progenitor/mid_leg_b_lower.png", new Vector2(265.500f, 290.000f), new Vector2(4.500f, -16.000f), 34, 14, 2, false, "limb"),
        new("mid_leg_b", "MidLegB", "res://images/monsters/rig_parts/bowlbug_progenitor/mid_leg_b.png", new Vector2(226.500f, 204.000f), new Vector2(-4.500f, -6.000f), 33, 20, 2, false, "limb"),
        new("rear_foot_a", "RearFootA", "res://images/monsters/rig_parts/bowlbug_progenitor/rear_foot_a.png", new Vector2(535.500f, 351.000f), new Vector2(-14.500f, -17.500f), 35, 10, 2, false, "foot"),
        new("rear_leg_a_lower", "RearLegALower", "res://images/monsters/rig_parts/bowlbug_progenitor/rear_leg_a_lower.png", new Vector2(463.500f, 285.000f), new Vector2(-5.500f, -7.500f), 34, 14, 2, false, "limb"),
        new("rear_leg_a", "RearLegA", "res://images/monsters/rig_parts/bowlbug_progenitor/rear_leg_a.png", new Vector2(409.500f, 204.000f), new Vector2(-3.500f, -3.500f), 33, 20, 2, false, "limb"),
        new("rear_foot_b", "RearFootB", "res://images/monsters/rig_parts/bowlbug_progenitor/rear_foot_b.png", new Vector2(692.500f, 329.000f), new Vector2(-18.500f, -14.500f), 35, 10, 2, false, "foot"),
        new("rear_leg_b_lower", "RearLegBLower", "res://images/monsters/rig_parts/bowlbug_progenitor/rear_leg_b_lower.png", new Vector2(645.500f, 275.000f), new Vector2(-23.500f, -2.000f), 34, 14, 2, false, "limb"),
        new("rear_leg_b", "RearLegB", "res://images/monsters/rig_parts/bowlbug_progenitor/rear_leg_b.png", new Vector2(601.500f, 204.000f), new Vector2(-12.500f, -5.000f), 33, 20, 2, false, "limb"),
        new("crest", "Crest", "res://images/monsters/rig_parts/bowlbug_progenitor/crest.png", new Vector2(-298.500f, -41.000f), new Vector2(-44.500f, -44.000f), 26, 10, 2, false, "armor"),
        new("head", "Head", "res://images/monsters/rig_parts/bowlbug_progenitor/head.png", new Vector2(-298.500f, 119.000f), new Vector2(-101.000f, 9.500f), 30, 14, 2, false, "head"),
        new("front_shell", "FrontShell", "res://images/monsters/rig_parts/bowlbug_progenitor/front_shell.png", new Vector2(-118.500f, 74.000f), new Vector2(90.500f, -176.000f), 21, 12, 2, false, "armor"),
        new("mid_shell", "MidShell", "res://images/monsters/rig_parts/bowlbug_progenitor/mid_shell.png", new Vector2(146.500f, 79.000f), new Vector2(106.500f, -195.500f), 22, 12, 2, false, "armor"),
        new("egg_sac", "EggSac", "res://images/monsters/rig_parts/bowlbug_progenitor/egg_sac.png", new Vector2(341.500f, 84.000f), new Vector2(81.500f, -128.000f), 20, 10, 2, false, "core"),
        new("rear_shell", "RearShell", "res://images/monsters/rig_parts/bowlbug_progenitor/rear_shell.png", new Vector2(541.500f, 109.000f), new Vector2(5.500f, -156.000f), 23, 12, 2, false, "armor"),
        new("socket_front_leg", "FrontShell", "res://images/monsters/rig_parts/bowlbug_progenitor/socket_front_leg.png", new Vector2(-118.500f, 74.000f), new Vector2(-22.000f, 128.000f), 31, 0, 2, true, "socket"),
        new("socket_mid_leg_a", "MidShell", "res://images/monsters/rig_parts/bowlbug_progenitor/socket_mid_leg_a.png", new Vector2(146.500f, 79.000f), new Vector2(-177.000f, 123.000f), 31, 0, 2, true, "socket"),
        new("socket_mid_leg_b", "EggSac", "res://images/monsters/rig_parts/bowlbug_progenitor/socket_mid_leg_b.png", new Vector2(341.500f, 84.000f), new Vector2(-117.000f, 118.000f), 31, 0, 2, true, "socket"),
        new("socket_rear_leg_a", "RearShell", "res://images/monsters/rig_parts/bowlbug_progenitor/socket_rear_leg_a.png", new Vector2(541.500f, 109.000f), new Vector2(-132.000f, 93.000f), 31, 0, 2, true, "socket"),
        new("socket_rear_leg_b", "RearShell", "res://images/monsters/rig_parts/bowlbug_progenitor/socket_rear_leg_b.png", new Vector2(541.500f, 109.000f), new Vector2(59.500f, 85.500f), 31, 0, 2, true, "socket"),
    ];

    private static readonly CutoutPartSpec[] ScaleBeetle =
    [
        new("base", "Root", "res://images/monsters/rig_parts/scale_beetle/base.png", new Vector2(46.500f, 208.500f), new Vector2(-177.000f, -177.000f), 0, 0, 2, false, "base"),
        new("antenna_front_base", "AntennaFrontBase", "res://images/monsters/rig_parts/scale_beetle/antenna_front_base.png", new Vector2(-437.500f, 110.500f), new Vector2(-1.500f, -19.500f), 60, 3, 2, false, "antenna"),
        new("antenna_front_1", "AntennaFront1", "res://images/monsters/rig_parts/scale_beetle/antenna_front_1.png", new Vector2(-426.500f, 40.500f), new Vector2(5.500f, -48.500f), 60, 3, 2, false, "antenna"),
        new("antenna_front_2", "AntennaFront2", "res://images/monsters/rig_parts/scale_beetle/antenna_front_2.png", new Vector2(-397.500f, -67.500f), new Vector2(3.000f, -39.500f), 60, 3, 2, false, "antenna"),
        new("antenna_front_3", "AntennaFront3", "res://images/monsters/rig_parts/scale_beetle/antenna_front_3.png", new Vector2(-342.500f, -149.500f), new Vector2(8.000f, -38.000f), 60, 3, 2, false, "antenna"),
        new("antenna_front_4", "AntennaFront4", "res://images/monsters/rig_parts/scale_beetle/antenna_front_4.png", new Vector2(-264.500f, -224.500f), new Vector2(13.500f, -28.500f), 60, 3, 2, false, "antenna"),
        new("antenna_front_5", "AntennaFront5", "res://images/monsters/rig_parts/scale_beetle/antenna_front_5.png", new Vector2(-171.500f, -278.500f), new Vector2(20.000f, -19.500f), 60, 3, 2, false, "antenna"),
        new("antenna_front_tip", "AntennaFrontTip", "res://images/monsters/rig_parts/scale_beetle/antenna_front_tip.png", new Vector2(-89.500f, -295.500f), new Vector2(35.000f, -19.500f), 60, 3, 2, false, "antenna"),
        new("antenna_back_base", "AntennaBackBase", "res://images/monsters/rig_parts/scale_beetle/antenna_back_base.png", new Vector2(-462.500f, 107.500f), new Vector2(-18.500f, -25.500f), 59, 3, 2, false, "antenna"),
        new("antenna_back_1", "AntennaBack1", "res://images/monsters/rig_parts/scale_beetle/antenna_back_1.png", new Vector2(-479.500f, 44.500f), new Vector2(-10.500f, -49.500f), 59, 3, 2, false, "antenna"),
        new("antenna_back_2", "AntennaBack2", "res://images/monsters/rig_parts/scale_beetle/antenna_back_2.png", new Vector2(-480.500f, -57.500f), new Vector2(2.500f, -47.500f), 59, 3, 2, false, "antenna"),
        new("antenna_back_3", "AntennaBack3", "res://images/monsters/rig_parts/scale_beetle/antenna_back_3.png", new Vector2(-443.500f, -155.500f), new Vector2(7.000f, -42.500f), 59, 3, 2, false, "antenna"),
        new("antenna_back_4", "AntennaBack4", "res://images/monsters/rig_parts/scale_beetle/antenna_back_4.png", new Vector2(-377.500f, -241.500f), new Vector2(11.000f, -37.500f), 59, 3, 2, false, "antenna"),
        new("antenna_back_5", "AntennaBack5", "res://images/monsters/rig_parts/scale_beetle/antenna_back_5.png", new Vector2(-303.500f, -320.500f), new Vector2(18.500f, -38.500f), 59, 3, 2, false, "antenna"),
        new("antenna_back_tip", "AntennaBackTip", "res://images/monsters/rig_parts/scale_beetle/antenna_back_tip.png", new Vector2(-233.500f, -382.500f), new Vector2(43.500f, -25.500f), 59, 3, 2, false, "antenna"),
        new("eye", "Head", "res://images/monsters/rig_parts/scale_beetle/eye.png", new Vector2(-213.500f, 158.500f), new Vector2(-192.000f, 53.500f), 42, 0, 2, true, "jaw_socket_bundle"),
        new("jaw_upper", "JawUpper", "res://images/monsters/rig_parts/scale_beetle/jaw_upper.png", new Vector2(-398.500f, 218.500f), new Vector2(-38.000f, 9.000f), 44, 10, 2, false, "jaw"),
        new("jaw_lower", "JawLower", "res://images/monsters/rig_parts/scale_beetle/jaw_lower.png", new Vector2(-383.500f, 248.500f), new Vector2(-7.000f, 5.000f), 45, 10, 2, false, "jaw"),
        new("fore_claw_tip", "ForeClawLower", "res://images/monsters/rig_parts/scale_beetle/fore_claw_tip.png", new Vector2(-230.500f, 313.500f), new Vector2(-205.500f, 72.500f), 42, 12, 2, false, "foot"),
        new("fore_claw_lower", "ForeClawLower", "res://images/monsters/rig_parts/scale_beetle/fore_claw_lower.png", new Vector2(-230.500f, 313.500f), new Vector2(-14.500f, 15.000f), 41, 16, 2, false, "limb"),
        new("fore_claw", "ForeClaw", "res://images/monsters/rig_parts/scale_beetle/fore_claw.png", new Vector2(-133.500f, 238.500f), new Vector2(-3.500f, -5.000f), 38, 20, 2, false, "limb"),
        new("front_foot", "FrontFoot", "res://images/monsters/rig_parts/scale_beetle/front_foot.png", new Vector2(-34.500f, 362.500f), new Vector2(21.500f, -15.000f), 31, 10, 2, false, "foot"),
        new("front_leg_lower", "FrontLegLower", "res://images/monsters/rig_parts/scale_beetle/front_leg_lower.png", new Vector2(-3.500f, 302.500f), new Vector2(13.500f, -16.000f), 30, 14, 2, false, "limb"),
        new("front_leg", "FrontLeg", "res://images/monsters/rig_parts/scale_beetle/front_leg.png", new Vector2(-33.500f, 238.500f), new Vector2(46.000f, -7.000f), 28, 18, 2, false, "limb"),
        new("mid_foot", "MidFoot", "res://images/monsters/rig_parts/scale_beetle/mid_foot.png", new Vector2(126.500f, 404.500f), new Vector2(15.500f, -3.000f), 36, 10, 2, false, "foot"),
        new("mid_leg_lower", "MidLegLower", "res://images/monsters/rig_parts/scale_beetle/mid_leg_lower.png", new Vector2(92.500f, 302.500f), new Vector2(19.500f, 1.000f), 35, 14, 2, false, "limb"),
        new("mid_leg", "MidLeg", "res://images/monsters/rig_parts/scale_beetle/mid_leg.png", new Vector2(56.500f, 208.500f), new Vector2(13.000f, -15.000f), 33, 18, 2, false, "limb"),
        new("rear_foot", "RearFoot", "res://images/monsters/rig_parts/scale_beetle/rear_foot.png", new Vector2(394.500f, 400.500f), new Vector2(4.500f, -14.000f), 37, 10, 2, false, "foot"),
        new("rear_leg_lower", "RearLegLower", "res://images/monsters/rig_parts/scale_beetle/rear_leg_lower.png", new Vector2(347.500f, 293.500f), new Vector2(6.000f, -12.500f), 36, 14, 2, false, "limb"),
        new("rear_leg", "RearLeg", "res://images/monsters/rig_parts/scale_beetle/rear_leg.png", new Vector2(302.500f, 183.500f), new Vector2(-7.500f, 0.500f), 34, 18, 2, false, "limb"),
        new("head", "Head", "res://images/monsters/rig_parts/scale_beetle/head.png", new Vector2(-213.500f, 158.500f), new Vector2(-59.000f, -96.500f), 30, 14, 2, false, "head"),
        new("front_shell", "FrontShell", "res://images/monsters/rig_parts/scale_beetle/front_shell.png", new Vector2(-58.500f, 113.500f), new Vector2(130.000f, -23.500f), 20, 10, 2, false, "armor"),
        new("core_shell", "Core", "res://images/monsters/rig_parts/scale_beetle/core_shell.png", new Vector2(126.500f, 103.500f), new Vector2(155.500f, 8.500f), 21, 10, 2, false, "armor"),
        new("rear_shell", "RearShell", "res://images/monsters/rig_parts/scale_beetle/rear_shell.png", new Vector2(336.500f, 123.500f), new Vector2(84.000f, 17.500f), 19, 10, 2, false, "armor"),
        new("socket_fore_claw", "FrontShell", "res://images/monsters/rig_parts/scale_beetle/socket_fore_claw.png", new Vector2(-58.500f, 113.500f), new Vector2(-69.500f, 20.500f), 26, 0, 2, true, "head_foreclaw_socket_bundle"),
        new("socket_front_leg", "FrontShell", "res://images/monsters/rig_parts/scale_beetle/socket_front_leg.png", new Vector2(-58.500f, 113.500f), new Vector2(23.000f, 123.000f), 26, 0, 2, true, "socket"),
        new("socket_mid_leg", "Core", "res://images/monsters/rig_parts/scale_beetle/socket_mid_leg.png", new Vector2(126.500f, 103.500f), new Vector2(-67.000f, 108.000f), 26, 0, 2, true, "socket"),
        new("socket_rear_leg", "RearShell", "res://images/monsters/rig_parts/scale_beetle/socket_rear_leg.png", new Vector2(336.500f, 123.500f), new Vector2(-32.000f, 63.000f), 26, 0, 2, true, "socket"),
    ];

    private static readonly CutoutPartSpec[] SoulRoe1 =
    [
        new("base", "Root", "res://images/monsters/rig_parts/soul_roe_1/base.png", new Vector2(0.000f, 0.000f), new Vector2(0.000f, 0.000f), 0, 0, 2, false, "base"),
        new("nucleus", "Nucleus", "res://images/monsters/rig_parts/soul_roe_1/nucleus.png", new Vector2(0.000f, 4.000f), new Vector2(1.000f, 1.000f), 3, 0, 2, false, "nucleus"),
        new("inner_halo", "Core", "res://images/monsters/rig_parts/soul_roe_1/inner_halo.png", new Vector2(0.000f, 4.000f), new Vector2(1.000f, 1.000f), 2, 0, 2, false, "halo"),
    ];

    private static readonly CutoutPartSpec[] SoulRoe2 =
    [
        new("base", "Root", "res://images/monsters/rig_parts/soul_roe_2/base.png", new Vector2(0.000f, 0.000f), new Vector2(0.000f, 0.000f), 0, 0, 2, false, "base"),
        new("nucleus", "Nucleus", "res://images/monsters/rig_parts/soul_roe_2/nucleus.png", new Vector2(0.000f, 4.000f), new Vector2(1.000f, 1.000f), 3, 0, 2, false, "nucleus"),
        new("inner_halo", "Core", "res://images/monsters/rig_parts/soul_roe_2/inner_halo.png", new Vector2(0.000f, 4.000f), new Vector2(1.000f, 1.000f), 2, 0, 2, false, "halo"),
    ];

    private static readonly CutoutPartSpec[] SoulRoe3 =
    [
        new("base", "Root", "res://images/monsters/rig_parts/soul_roe_3/base.png", new Vector2(0.000f, 0.000f), new Vector2(0.000f, 0.000f), 0, 0, 2, false, "base"),
        new("nucleus", "Nucleus", "res://images/monsters/rig_parts/soul_roe_3/nucleus.png", new Vector2(0.000f, 4.000f), new Vector2(1.000f, 1.000f), 3, 0, 2, false, "nucleus"),
        new("inner_halo", "Core", "res://images/monsters/rig_parts/soul_roe_3/inner_halo.png", new Vector2(0.000f, 4.000f), new Vector2(1.000f, 1.000f), 2, 0, 2, false, "halo"),
    ];

    private static readonly CutoutPartSpec[] SoulRoes =
    [
        new("roe_bottom_right", "RoeBottomRight", "res://images/monsters/rig_parts/soul_roes/roe_bottom_right.png", new Vector2(81.500f, 86.500f), new Vector2(18.500f, -3.500f), 10, 0, 2, false, "orb"),
        new("roe_bottom", "RoeBottom", "res://images/monsters/rig_parts/soul_roes/roe_bottom.png", new Vector2(-0.500f, 81.500f), new Vector2(1.000f, 3.500f), 9, 0, 2, false, "orb"),
        new("roe_bottom_left", "RoeBottomLeft", "res://images/monsters/rig_parts/soul_roes/roe_bottom_left.png", new Vector2(-74.500f, 74.500f), new Vector2(-30.500f, 10.500f), 8, 0, 2, false, "orb"),
        new("roe_far_right", "RoeFarRight", "res://images/monsters/rig_parts/soul_roes/roe_far_right.png", new Vector2(144.500f, 43.500f), new Vector2(3.000f, 15.000f), 7, 0, 2, false, "orb"),
        new("roe_bottom_far_right", "RoeBottomFarRight", "res://images/monsters/rig_parts/soul_roes/roe_bottom_far_right.png", new Vector2(131.500f, 35.500f), new Vector2(-5.500f, -17.500f), 6, 0, 2, false, "orb"),
        new("roe_middle_left", "RoeMiddleLeft", "res://images/monsters/rig_parts/soul_roes/roe_middle_left.png", new Vector2(-63.500f, -1.500f), new Vector2(1.000f, -2.000f), 5, 0, 2, false, "orb"),
        new("roe_middle_far_left", "RoeMiddleFarLeft", "res://images/monsters/rig_parts/soul_roes/roe_middle_far_left.png", new Vector2(-140.500f, 5.500f), new Vector2(3.000f, 16.500f), 4, 0, 2, false, "orb"),
        new("roe_core", "RoeCore", "res://images/monsters/rig_parts/soul_roes/roe_core.png", new Vector2(4.500f, -14.500f), new Vector2(4.500f, 2.500f), 4, 0, 2, false, "orb"),
        new("roe_middle_right", "RoeMiddleRight", "res://images/monsters/rig_parts/soul_roes/roe_middle_right.png", new Vector2(91.500f, -24.500f), new Vector2(20.000f, -29.000f), 3, 0, 2, false, "orb"),
        new("roe_top_left", "RoeTopLeft", "res://images/monsters/rig_parts/soul_roes/roe_top_left.png", new Vector2(-98.500f, -67.500f), new Vector2(-17.000f, -12.000f), 2, 0, 2, false, "orb"),
        new("roe_top", "RoeTop", "res://images/monsters/rig_parts/soul_roes/roe_top.png", new Vector2(-33.500f, -91.500f), new Vector2(-4.000f, 1.500f), 1, 0, 2, false, "orb"),
        new("roe_top_right", "RoeTopRight", "res://images/monsters/rig_parts/soul_roes/roe_top_right.png", new Vector2(41.500f, -84.500f), new Vector2(44.000f, -3.000f), 1, 0, 2, false, "orb"),
    ];

    private static readonly CutoutPartSpec[] TheLegacy =
    [
        new("base", "Root", "res://images/monsters/rig_parts/the_legacy/base.png", new Vector2(1.000f, 215.500f), new Vector2(-101.500f, -215.500f), 0, 0, 2, false, "base"),
        new("coral_left", "CoralLeft", "res://images/monsters/rig_parts/the_legacy/coral_left.png", new Vector2(-379.000f, 85.500f), new Vector2(4.000f, 4.000f), 40, 0, 2, false, "coral"),
        new("coral_right", "CoralRight", "res://images/monsters/rig_parts/the_legacy/coral_right.png", new Vector2(126.000f, 215.500f), new Vector2(53.000f, 11.500f), 41, 0, 2, false, "coral"),
        new("seaweed_left", "SeaweedLeft", "res://images/monsters/rig_parts/the_legacy/seaweed_left.png", new Vector2(-419.000f, 5.500f), new Vector2(11.500f, -8.500f), 8, 0, 2, false, "vegetation"),
        new("seaweed_right", "Root", "res://images/monsters/rig_parts/the_legacy/seaweed_right.png", new Vector2(1.000f, 215.500f), new Vector2(262.500f, -206.500f), 8, 0, 2, false, "vegetation"),
        new("top_tubes", "TopTubes", "res://images/monsters/rig_parts/the_legacy/top_tubes.png", new Vector2(11.000f, -229.500f), new Vector2(41.000f, -11.500f), 18, 0, 2, false, "vessel"),
        new("top_purple", "TopPurple", "res://images/monsters/rig_parts/the_legacy/top_purple.png", new Vector2(111.000f, -174.500f), new Vector2(57.500f, 28.000f), 10, 0, 2, false, "organ"),
        new("left_tubes", "LeftTubes", "res://images/monsters/rig_parts/the_legacy/left_tubes.png", new Vector2(-329.000f, -69.500f), new Vector2(28.000f, 14.500f), 20, 0, 2, false, "vessel"),
        new("left_lobe", "LeftLobe", "res://images/monsters/rig_parts/the_legacy/left_lobe.png", new Vector2(-339.000f, 85.500f), new Vector2(25.500f, 25.500f), 21, 0, 2, false, "organ"),
        new("bottom_lobe", "BottomLobe", "res://images/monsters/rig_parts/the_legacy/bottom_lobe.png", new Vector2(-259.000f, 220.500f), new Vector2(46.500f, -7.000f), 22, 0, 2, false, "organ"),
        new("heart_core", "HeartCore", "res://images/monsters/rig_parts/the_legacy/heart_core.png", new Vector2(11.000f, 85.500f), new Vector2(152.000f, 80.000f), 25, 0, 2, false, "organ"),
        new("right_lobe", "RightLobe", "res://images/monsters/rig_parts/the_legacy/right_lobe.png", new Vector2(251.000f, 95.500f), new Vector2(102.000f, 18.500f), 23, 0, 2, false, "organ"),
        new("right_tubes", "RightTubes", "res://images/monsters/rig_parts/the_legacy/right_tubes.png", new Vector2(441.000f, 65.500f), new Vector2(90.000f, -22.000f), 26, 0, 2, false, "vessel"),
        new("right_purple_tubes", "RightPurpleTubes", "res://images/monsters/rig_parts/the_legacy/right_purple_tubes.png", new Vector2(551.000f, 175.500f), new Vector2(18.000f, 71.000f), 17, 0, 2, false, "vessel"),
    ];

    private static readonly CutoutPartSpec[] ThiefRaider =
    [
        new("dagger", "Dagger", "res://images/monsters/rig_parts/thief_raider/dagger.png", new Vector2(133.500f, 33.000f), new Vector2(5.000f, 23.000f), 50, 6, 2, false, "weapon"),
        new("dagger_hand", "DaggerHand", "res://images/monsters/rig_parts/thief_raider/dagger_hand.png", new Vector2(120.500f, 23.000f), new Vector2(-18.000f, -1.500f), 48, 8, 2, false, "hand"),
        new("dagger_forearm", "DaggerForearm", "res://images/monsters/rig_parts/thief_raider/dagger_forearm.png", new Vector2(105.500f, -32.000f), new Vector2(-18.500f, 13.000f), 46, 10, 2, false, "limb"),
        new("dagger_upper_arm", "DaggerUpperArm", "res://images/monsters/rig_parts/thief_raider/dagger_upper_arm.png", new Vector2(83.500f, -97.000f), new Vector2(-21.000f, 10.500f), 43, 12, 2, false, "limb"),
        new("guard_hand", "GuardHand", "res://images/monsters/rig_parts/thief_raider/guard_hand.png", new Vector2(-13.500f, -95.000f), new Vector2(10.000f, 1.000f), 46, 8, 2, false, "hand"),
        new("guard_forearm", "GuardForearm", "res://images/monsters/rig_parts/thief_raider/guard_forearm.png", new Vector2(-71.500f, -82.000f), new Vector2(10.500f, 3.000f), 44, 10, 2, false, "limb"),
        new("guard_arm", "GuardArm", "res://images/monsters/rig_parts/thief_raider/guard_arm.png", new Vector2(-56.500f, -132.000f), new Vector2(-7.500f, -20.000f), 42, 12, 2, false, "limb"),
        new("scarf", "Scarf", "res://images/monsters/rig_parts/thief_raider/scarf.png", new Vector2(30.500f, -122.000f), new Vector2(2.500f, -3.500f), 40, 8, 2, false, "cloth"),
        new("face_shadow", "Head", "res://images/monsters/rig_parts/thief_raider/face_shadow.png", new Vector2(13.500f, -142.000f), new Vector2(-2.000f, -65.000f), 39, 4, 2, false, "accent"),
        new("head", "Head", "res://images/monsters/rig_parts/thief_raider/head.png", new Vector2(13.500f, -142.000f), new Vector2(-13.500f, -77.500f), 38, 8, 2, false, "head"),
        new("torso", "Torso", "res://images/monsters/rig_parts/thief_raider/torso.png", new Vector2(13.500f, -32.000f), new Vector2(36.000f, -9.500f), 25, 8, 2, false, "core"),
        new("pelvis", "Pelvis", "res://images/monsters/rig_parts/thief_raider/pelvis.png", new Vector2(13.500f, 18.000f), new Vector2(0.000f, -3.000f), 24, 8, 2, false, "core"),
        new("left_foot", "LeftFoot", "res://images/monsters/rig_parts/thief_raider/left_foot.png", new Vector2(-58.500f, 228.000f), new Vector2(-13.500f, -6.500f), 21, 8, 2, false, "foot"),
        new("left_shin", "LeftShin", "res://images/monsters/rig_parts/thief_raider/left_shin.png", new Vector2(-41.500f, 143.000f), new Vector2(-2.000f, -5.500f), 19, 10, 2, false, "limb"),
        new("left_leg", "LeftLeg", "res://images/monsters/rig_parts/thief_raider/left_leg.png", new Vector2(-31.500f, 53.000f), new Vector2(-2.000f, 8.500f), 17, 12, 2, false, "limb"),
        new("right_foot", "RightFoot", "res://images/monsters/rig_parts/thief_raider/right_foot.png", new Vector2(75.500f, 218.000f), new Vector2(2.500f, -17.500f), 22, 8, 2, false, "foot"),
        new("right_shin", "RightShin", "res://images/monsters/rig_parts/thief_raider/right_shin.png", new Vector2(48.500f, 138.000f), new Vector2(13.000f, -7.500f), 20, 10, 2, false, "limb"),
        new("right_leg", "RightLeg", "res://images/monsters/rig_parts/thief_raider/right_leg.png", new Vector2(43.500f, 53.000f), new Vector2(72.000f, 4.500f), 18, 12, 2, false, "limb"),
        new("bag", "Bag", "res://images/monsters/rig_parts/thief_raider/bag.png", new Vector2(-50.500f, -122.000f), new Vector2(-21.000f, 1.000f), 5, 8, 2, false, "prop"),
        new("cloak_left_tail", "CloakLeftTail", "res://images/monsters/rig_parts/thief_raider/cloak_left_tail.png", new Vector2(-107.500f, 33.000f), new Vector2(-16.000f, 0.000f), 9, 10, 2, false, "cloth"),
        new("cloak_right_tail", "CloakRightTail", "res://images/monsters/rig_parts/thief_raider/cloak_right_tail.png", new Vector2(-26.500f, 48.000f), new Vector2(44.000f, -112.500f), 10, 10, 2, false, "cloth"),
        new("cloak", "Cloak", "res://images/monsters/rig_parts/thief_raider/cloak.png", new Vector2(-31.500f, -77.000f), new Vector2(-120.000f, -29.500f), 6, 10, 2, false, "cloth"),
        new("socket_guard_shoulder", "Torso", "res://images/monsters/rig_parts/thief_raider/socket_guard_shoulder.png", new Vector2(13.500f, -32.000f), new Vector2(-73.000f, -97.000f), 39, 0, 2, true, "socket"),
        new("socket_dagger_shoulder", "Torso", "res://images/monsters/rig_parts/thief_raider/socket_dagger_shoulder.png", new Vector2(13.500f, -32.000f), new Vector2(61.500f, -72.000f), 39, 0, 2, true, "socket"),
        new("socket_left_hip", "Pelvis", "res://images/monsters/rig_parts/thief_raider/socket_left_hip.png", new Vector2(13.500f, 18.000f), new Vector2(-42.000f, 28.000f), 15, 0, 2, true, "socket"),
        new("socket_right_hip", "Pelvis", "res://images/monsters/rig_parts/thief_raider/socket_right_hip.png", new Vector2(13.500f, 18.000f), new Vector2(30.500f, 30.500f), 15, 0, 2, true, "socket"),
    ];

    internal static IReadOnlyList<CutoutBoneSpec> GetBones(string key)
    {
        return key switch
        {
            "origin_fogmog" => OriginFogmogBones,
            "bowlbug_progenitor" => BowlbugProgenitorBones,
            "scale_beetle" => ScaleBeetleBones,
            "soul_roe_1" => SoulRoe1Bones,
            "soul_roe_2" => SoulRoe2Bones,
            "soul_roe_3" => SoulRoe3Bones,
            "soul_roes" => SoulRoesBones,
            "the_legacy" => TheLegacyBones,
            "thief_raider" => ThiefRaiderBones,
            _ => throw new KeyNotFoundException($"Unknown cutout rig key: {key}")
        };
    }

    internal static IReadOnlyList<CutoutPartSpec> Get(string key)
    {
        return key switch
        {
            "origin_fogmog" => OriginFogmog,
            "bowlbug_progenitor" => BowlbugProgenitor,
            "scale_beetle" => ScaleBeetle,
            "soul_roe_1" => SoulRoe1,
            "soul_roe_2" => SoulRoe2,
            "soul_roe_3" => SoulRoe3,
            "soul_roes" => SoulRoes,
            "the_legacy" => TheLegacy,
            "thief_raider" => ThiefRaider,
            _ => throw new KeyNotFoundException($"Unknown cutout rig key: {key}")
        };
    }
}
